// <auto-generated />
namespace AOCMDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removed_more_fields_made_redundant_by_audit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_more_fields_made_redundant_by_audit));
        
        string IMigrationMetadata.Id
        {
            get { return "201507010146483_removed_more_fields_made_redundant_by_audit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
