// <auto-generated />
namespace AOCMDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fixed_Upstream_Key_app_to_software_Server_Name_Added_Indexes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fixed_Upstream_Key_app_to_software_Server_Name_Added_Indexes));
        
        string IMigrationMetadata.Id
        {
            get { return "201505020605035_Fixed_Upstream_Key_app_to_software_Server_Name_Added_Indexes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
