// <auto-generated />
namespace AOCMDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Trying_out_inheritance_model_for_dependencies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Trying_out_inheritance_model_for_dependencies));
        
        string IMigrationMetadata.Id
        {
            get { return "201506270511149_Trying_out_inheritance_model_for_dependencies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
