// <auto-generated />
namespace AOCMDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Support_for_HTML_in_Application_Fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Support_for_HTML_in_Application_Fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201504120723593_Support_for_HTML_in_Application_Fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
