// <auto-generated />
namespace AOCMDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removed_Dependency_revision_since_audit_table_exists : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removed_Dependency_revision_since_audit_table_exists));
        
        string IMigrationMetadata.Id
        {
            get { return "201507010120059_Removed_Dependency_revision_since_audit_table_exists"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
