// <auto-generated />
namespace AOCMDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fixed_Server_Name_Added_Indexes_to_Names : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fixed_Server_Name_Added_Indexes_to_Names));
        
        string IMigrationMetadata.Id
        {
            get { return "201505020511219_Fixed_Server_Name_Added_Indexes_to_Names"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
