// <auto-generated />
namespace AOCMDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Correct_the_software_Framework_id_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Correct_the_software_Framework_id_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201505020657263_Correct_the_software_Framework_id_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
